version: '3'
services:
  flask_ftw:
    build:
      context: ./back_pain
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5000:5000"
  react_l:
    build:
      context: ./front_shit
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development 
    depends_on:
      - flask_ftw
  mongo:
    image: mongo
    hostname: test_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
